Created new Favorites Menu as described in the issue #884
microsoft/vscode-maven pull request #900
Opened 2022-11-06 17:46 UTC by gustavosimon

2022-11-07 02:23 UTC, Eskibear requested changes
Thanks for contribution! Basically it works well. Some nits:
- display `command` in tree item as commented in line.

Further improvements:
a) when `maven.terminal.favorites` is not configured, it's strange to display empty children, and you get no idea whether it's broken or how to add favorite items. 
I would suggest we add a "+" button as inline action of FavoriteMenu, which provides a UI (e.g. quickpick/input) to add corresponding items.

b) Currently when I change the corresponding setting, I have to manually click the refresh button to get the tree items updated. Listening to the change and refresh tree view would be better. In fact it can be implemented by `vscode.workspace.onDidChangeConfiguration` API.

c) Currently the setting is shared among all projects, meaning you set favorite commands for all projects and have no change to customize it for each project. But for each project in the tree view, there is a corresponding menu, which is a little bit inconsistent and strange. Not sure whether we should allow to configure it per project.

For above further thoughts, it's ok not to address in this PR, but to create new issues to track.

2022-11-07 02:23 UTC, Eskibear commented on src/explorer/model/FavoriteCommand.ts
> +        const treeItem: vscode.TreeItem = new vscode.TreeItem(this.alias, vscode.TreeItemCollapsibleState.None);
would be better if it displays real 'command' along with 'alias', to distinguish from each other, as below.
```
treeItem.description = this.command;
```

<img width="340" alt="image" src="https://user-images.githubusercontent.com/2351748/200212363-3e91beeb-99cc-484f-a50d-160af54682b0.png">

2022-11-07 14:22 UTC, gustavosimon commented
Hi @Eskibear ! Thanks for feedback 😀!

I will add the `command` in tree item as commented in line. The idea is awesome.

About `a` and `b` items, I really appreciate the idea. I think that we can create a new enhancement issue to improve this behaviors.

About `c` item, I just take the same behavior about the LifecycleMenu, because this commands was list for each project.
How can we track this one?

![image](https://user-images.githubusercontent.com/25882357/200332449-bd33a519-f6bb-47df-9dc6-4ea35c6f90f4.png)

Btw, just for curiousity: What's the meaning of `nits`? It is like a note/observation?

2022-11-08 00:37 UTC, Eskibear commented
> About a and b items, I really appreciate the idea. I think that we can create a new enhancement issue to improve this behaviors.

Great!

> About c item, I just take the same behavior about the LifecycleMenu

IMO there's a little difference. Items listed under LifecycleMenu are just basic phases common for every Maven project, even the simplest ones. Favorite commands are customized by users, for example I can add a "spring-boot:run" for a SpringBoot project, but it doesn't make sense to show under a non-SpringBoot project which has no spring-boot-maven-plugin configured.

Anyway, it's good and we can leave it as is now. Let's consider the improvement when we receive requests from community...


> What's the meaning of nits

from "nitpicking", meaning minor things nice to improve. never mind.

2022-11-08 02:10 UTC, gustavosimon commented
Nice! I will create the issue tomorrow for we improve this implementation as described on item a and b.

> IMO there's a little difference. Items listed under LifecycleMenu are just basic phases common for every Maven project, even the simplest ones. Favorite commands are customized by users, for example I can add a "spring-boot:run" for a SpringBoot project, but it doesn't make sense to show under a non-SpringBoot project which has no spring-boot-maven-plugin configured.

You're right. It makes sense. Let's consider thinking to improve this behavior to in future.

I saw that the pipelines failed. Should I do something to fix this?

> Anyway, it's good and we can leave it as is now. Let's consider the improvement when we receive requests from community...

Good. Feel free to ask me for help in any issue. I daily use this extension and really would like to help to improve it more.

2022-11-08 06:56 UTC, Eskibear commented
linting issue, you can run `npm run tslint` locally to do the check.

```
ERROR: (no-shadowed-variable) /home/runner/work/vscode-maven/vscode-maven/src/Settings.ts[66, 19]: Shadowed name: 'favorites'
ERROR: (no-trailing-whitespace) /home/runner/work/vscode-maven/vscode-maven/src/explorer/model/FavoriteCommand.ts[10, 1]: trailing whitespace
ERROR: (no-trailing-whitespace) /home/runner/work/vscode-maven/vscode-maven/src/explorer/model/FavoriteCommand.ts[23, 1]: trailing whitespace
ERROR: (no-trailing-whitespace) /home/runner/work/vscode-maven/vscode-maven/src/explorer/model/ITreeItem.ts[14, 1]: trailing whitespace
ERROR: (no-trailing-whitespace) /home/runner/work/vscode-maven/vscode-maven/src/utils/Utils.ts[262, 1]: trailing whitespace
```

2022-11-08 06:57 UTC, Eskibear commented
/azp run

2022-11-08 11:38 UTC, gustavosimon commented
Hello @Eskibear. Fixed linting issues. Can you trigger the pipeline again?

2022-11-08 12:24 UTC, Eskibear commented
/azp run

2022-11-08 12:56 UTC, Eskibear commented
TS compiler also complains. If you don't mind, I can fix the errors. Then you can take your time to focus on the rest work.

2022-11-08 13:04 UTC, gustavosimon commented
Sure! Thank you @Eskibear.

2022-11-09 01:53 UTC, Eskibear approved these changes

2022-11-09 01:54 UTC, Eskibear approved these changes

2022-11-09 01:54 UTC, merged